In [23]:
import numpy as np
from scipy import linalg

In [24]:
#zadanie 1

def my_gaus_elim(A):
    n = A.shape[0]
    #x = np.zeros(n,np.float32)
    for k in range(n-1):
        #przerzucam zera na koniec
        if np.abs(A[k,k]) < 1.0e-20:
            for i in range(k+1, n):
                if np.abs(A[i,k]) > np.abs(A[k,k]):
                    A[[k,i]] = A[[i,k]]
        #eliminacja kolumny
        for i in range(k+1,n):
            if A[i,k] == 0: 
                continue
            ratio = A[k,k]/A[i,k]
            for j in range(k, n): 
                A[i,j] = A[k,j] - A[i,j]*ratio
    return A
A = np.array([
    [1, 2, 4, 2], 
    [2, 4, 5, 1], 
    [0, 0, 0, 12], 
    [3, 2, 4, 5]])
print(my_gaus_elim(A))

[[ 1  2  4  2]
 [ 0  1  2  0]
 [ 0  0  1  1]
 [ 0  0  0 12]]


In [29]:
# zadanie 2 

#funkcja z zajec
def solve_upper_triangular(A, y):
    x = np.zeros(y.shape)
    for i in range(len(y) - 1, -1, -1):
        if i == len(y) - 1:
            x[i] = y[i] / A[i, i]
        else:
            ratio = 1 / A[i, i]
            x[i] = ratio * (y[i] - np.sum(A[i, i+1:] @ x[i+1:]))
    return x


def our_solve_eq(A,y):

    n = y.shape[0]
    x = np.zeros(n,np.float32)

    for k in range(n-1):
        if np.abs(A[k,k]) < 1.0e-9:
            for i in range(k+1, n):
                if np.abs(A[i,k]) > np.abs(A[k,k]):
                    A[[k,i]] = A[[i,k]]
                    y[[k,i]] = y[[i,k]]
        for i in range(k+1,n):
            if A[i,k] == 0: 
                continue
            ratio = A[k,k]/A[i,k]
            for j in range(k, n): 
                A[i,j] = A[k,j] - A[i,j]*ratio
            y[i] = y[k] - y[i]*temp
    x[n-1] = y[n-1]/A[n-1, n-1]
    for i in range(n - 2, -1, -1):  #ostatnie juz rozwiazane wiec zaczynam od n-2
        sum = 0
        for j in range(i + 1, n):
            sum = sum + (A[i, j] * x[j])
        x[i] = (y[i] - sum) / A[i, i]
    return solve_upper_triangular(A,y)

A = np.array([
    [2, 3, 5],
    [0, 2, 3],
    [0, 0, 2],
], dtype=np.float32)
y = np.array([10, 7, 4])

print("Solution from our: ", our_solve_eq(A,y))
print("Solution from linalg numpy:", np.linalg.solve(A,y))

Solution from our:  [-0.75  0.5   2.  ]
Solution from linalg numpy: [-0.75  0.5   2.  ]


In [32]:
# zadanie 3


def solve_lower_triangular(A, y):
    x = np.zeros(y.shape)
    for i in range(0, len(y), 1):
        if i == 0:
            x[i] = y[i] / A[i, i]
        else:
            ratio = 1 / A[i, i]
            x[i] = ratio * (y[i] - np.sum(A[i, :i] @ x[:i]))
    return x


A = np.array([
    [2, 3, 5, 4, 1, 5, 9, 6],
    [1, 5, 1, 7, 1, 2, 1, 6],
    [2, 1, 1, 6, 9, 8, 7, 4],
    [4, 5, 8, 2, 6, 2, 5, 1],
    [2, 3, 1, 1, 9, 2, 10, 1],
    [3, 5, 4, 6, 7, 1, 2, 7],
    [3, 6, 7, 6, 7, 5, 5, 6],
    [4, 5, 4, 7, 8, 1, 1, 3]]
)

y = np.array([5, 7, 9, 3, 9, 5, 10, 5])
np.set_printoptions(precision=3)
p, L, U = linalg.lu(A)
print("p: ")
print(p)
print("L: ")
print(L)
print("U: ")
print(U)


d = solve_lower_triangular(L, y @ p)
x = solve_upper_triangular(U, d)


x_lib = linalg.solve(A, y)
print("Solutions")
print(x)
print(x_lib)

p: 
[[0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]]
L: 
[[ 1.     0.     0.     0.     0.     0.     0.     0.   ]
 [ 0.25   1.     0.     0.     0.     0.     0.     0.   ]
 [ 1.     0.     1.     0.     0.     0.     0.     0.   ]
 [ 0.5    0.133  0.717  1.     0.     0.     0.     0.   ]
 [ 0.5   -0.4    0.85  -0.753  1.     0.     0.     0.   ]
 [ 0.75   0.6   -0.4   -0.584  0.831  1.     0.     0.   ]
 [ 0.5    0.133 -0.283 -0.798  0.307 -0.365  1.     0.   ]
 [ 0.75   0.333  0.417 -0.056  0.276  0.644  0.135  1.   ]]
U: 
[[ 4.     5.     8.     2.     6.     2.     5.     1.   ]
 [ 0.     3.75  -1.     6.5   -0.5    1.5   -0.25   5.75 ]
 [ 0.     0.    -4.     5.     2.    -1.    -4.     2.   ]
 [ 0.     0.     0.    -4.45   4.633  1.517 10.4   -1.7  ]
 [ 0.     0.     0.     0.     7.588  9.592 15.629  2.82 ]
 [ 